version: '3.8'

services:
  ai-solver:
    build: .
    container_name: ai-solver-container

    volumes:
      - ./plots:/app/plots

    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2.0'