version: '3.8'

services:
  ai-solver:
    build: .
    user: "1007:1007"

    volumes:
      - ./plot:/app/plot
      - ./wysylka:/app/wysylka

    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2.0'