from tasks.ai.article.examples.first.FirstProblemSimpleTask import FirstProblemSimpleTask
from tasks.ai.article.examples.first.FirstProblemLossTask import FirstProblemLossTask
from tasks.ai.article.examples.first.FirstProblemLossWithWeightTask import FirstProblemLossWithWeightTask
