name: Create stats plots

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  prepare-and-get-paths:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-paths.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
      - name: Deploy to VPS, Run Scripts and Get Paths
        id: get-paths
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e
            
            # Przechodzimy do folderu (używamy ~ by automatycznie trafić do /home/user)
            cd ~/Differential-Equations-Solver

            BRANCH="${{ github.ref_name }}"
            echo "▶ Deploying branch: $BRANCH"
            git fetch origin
            git checkout $BRANCH
            git reset --hard origin/$BRANCH

            echo "▶ Building Docker image"
            docker compose build

            echo "▶ Stating Solver - HeatmapScript.py"
            mkdir -p plot
            docker compose run --rm ai-solver python bin/HeatmapScript.py

            echo "▶ Stating Solver - Copy_Plots.py"
            docker compose run --rm ai-solver python bin/Copy_Plots.py

            echo "▶ Stating Solver - GetPlotsPaths.py"
            # Ważne: to musi być wewnątrz bloku EOF!
            docker compose run --rm ai-solver python bin/GetPlotsPaths.py > paths_output.json
          EOF

          echo "▶ Downloading paths_output.json from VPS"
          # Odczytujemy plik z poziomu runnera Githuba, odnosząc się znowu przez ~
          PATHS_JSON=$(ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cat ~/Differential-Equations-Solver/paths_output.json")
          
          echo "Pobrane ścieżki: $PATHS_JSON"
          echo "matrix=$PATHS_JSON" >> $GITHUB_OUTPUT
      

  compile-plots:
    needs: prepare-and-get-paths
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.prepare-and-get-paths.outputs.matrix) }}

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Run Compile_plots.py in parallel
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e
            cd /home/python/Differential-Equations-Solver
            
            echo "▶ Running Compile_plots.py for path: ${{ matrix.path }}"
            # Przekazanie ścieżki z zachowaniem cudzysłowów (odporne na spacje)
            docker compose run --rm ai-solver python bin/Compile_plots.py "${{ matrix.path }}"
          EOF