name: Create stats plots

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  prepare-and-get-paths:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-paths.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS and Run Scripts
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            # UWAGA: Usunięto set -e, aby błędy zamykania Dockera nie urywały połączenia SSH
            cd ~/Differential-Equations-Solver

            BRANCH="${{ github.ref_name }}"
            echo "▶ Deploying branch: $BRANCH"
            git fetch origin
            git checkout $BRANCH
            git reset --hard origin/$BRANCH

            echo "▶ Building Docker image"
            docker compose build

            echo "▶ Stating Solver - HeatmapScript.py"
            mkdir -p plot
            #docker compose run --rm ai-solver python bin/HeatmapScript.py || true

            echo "▶ Stating Solver - Copy_Plots.py"
            mkdir -p wysylka
            docker compose run --rm ai-solver python bin/Copy_Plots.py || true
          EOF

      - name: Run GetPlotsPaths.py (fetch directly from VPS)
        id: get-paths
        run: |
          # Łączymy się z VPS, przechodzimy do projektu i zlecamy uruchomienie skryptu przez środowisko dockera.
          # Używamy jq, aby upewnić się, że śmieci z logów dockera nie popsują formatu JSON!
          
          echo "▶ Running GetPlotsPaths on VPS and fetching result..."
          PATHS_JSON=$(ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd ~/Differential-Equations-Solver && docker compose run --quiet-pull --rm ai-solver python bin/GetPlotsPaths.py | grep '\['")
          
          echo "Pobrane ścieżki: $PATHS_JSON"
          echo "matrix=$PATHS_JSON" >> $GITHUB_OUTPUT

  compile-plots:
    needs: prepare-and-get-paths
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        path: ${{ fromJson(needs.prepare-and-get-paths.outputs.matrix) }}

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Run Compile_plots.py in parallel
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ~/Differential-Equations-Solver
            
            echo "▶ Running Compile_plots.py for path: ${{ matrix.path }}"
            docker compose run --rm ai-solver python bin/Compile_plots.py "${{ matrix.path }}"
          EOF